apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: '@hourly'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              # Update this to the latest available and then enable Renovate on
              # the manifest
              image: renovate/renovate:32.194.0
              # Environment Variables
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_AUTODISCOVER
                  value: 'true'
              envFrom:
                - secretRef:
                    name: renovate-env
          dnsConfig:
            nameservers:
            - 8.8.8.8
            - 8.8.4.4
          restartPolicy: Never
